apps/bow_hunt/urls.py
from django.conf.urls import url

from .add import AddIPDFinalReport, AddLogs, AddNonIPDLogs, FetchLogSheetData
from .commons import CommonsHunting
from .daily_log_sheets import FetchLogSheetsByYear, LogSheetView
from .analysis import HunterAnalysis, LocationAnalysis, SiteAnalysis

app_name = 'bow_hunt'
urlpatterns = [
    url(r'^analysis/by_hunter/$', HunterAnalysis.as_view(), name='hunter_analysis'),
    url(r'^analysis/by_location/$', LocationAnalysis.as_view(), name='location_analysis'),
    url(r'^analysis/by_site/$', SiteAnalysis.as_view(), name='site_analysis'),
    url(r'^commons/$', CommonsHunting.as_view(), name='commons_hunting'),
    url(r'^log_sheet/$', LogSheetView.as_view(), name='log_sheet'),
    url(r'^log_sheet/add/ipd_final_report/$', AddIPDFinalReport.as_view(), name='add_ipd_final_report'),
    url(r'^log_sheet/add/logs/$', AddLogs.as_view(), name='add_logs'),
    url(r'^log_sheet/add/non_ipd_logs/$', AddNonIPDLogs.as_view(), name='add_non_ipd_logs'),
    url(r'^log_sheet/fetch/by_year/locations/$', FetchLogSheetData.as_view(), name='fetch_log_sheet_data'),
    url(r'^log_sheet/fetch/by_year/log_sheets/$', FetchLogSheetsByYear.as_view(), name='fetch_log_sheet_by_year')
]

apps/residents/urls.py
from django.conf.urls import url

from .views import BoardMembersListView, MainMenuView, ResidentListView

app_name = 'resident'
urlpatterns = [
    url(r'^board_members/$', BoardMembersListView.as_view(), name='board'),
    url(r'^information/$', ResidentListView.as_view(), name='information'),
    url(r'^main_menu/$', MainMenuView.as_view(), name='main_menu')
]

hh/urls.py
"""hh URL Configuration
"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView

from library.views.generic import ProtectedMedia

urlpatterns = ([
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authentication.urls')),
    url(r'^bow_hunt/', include('bow_hunt.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^history/', include('history.urls')),
    url(r'^mailing_lists/', include('mailing_lists.urls')),
    url(r'^media/members/(?:.*)$', ProtectedMedia.as_view(), name='media'),
    url(r'^news/', include('news.urls')),
    url(r'^resident/', include('residents.urls')),
    url(r'^search/$', TemplateView.as_view(template_name='search.html'), name='search'),
    url(r'^staff/', include('staff.urls')),
    url(r'^technical/$', TemplateView.as_view(template_name='technical.html'), name='technical'),
    url(r'^tinymce/', include('tinymce.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

apps/residents/models.py
# noinspection PyPackageRequirements
from localflavor.us.models import USStateField

from phonenumber_field.modelfields import PhoneNumberField

from django.db import models

from library.models import SingletonModel


class Board(SingletonModel):
    director_at_large_1 = models.ForeignKey('Person', blank=True, related_name='director_at_large_1')
    director_at_large_2 = models.ForeignKey('Person', blank=True, related_name='director_at_large_2')
    president = models.ForeignKey('Person', blank=True, related_name='president')
    secretary = models.ForeignKey('Person', blank=True, related_name='secretary')
    treasurer = models.ForeignKey('Person', blank=True, related_name='treasurer')
    vice_president = models.ForeignKey('Person', blank=True, related_name='vice_president')

    class Meta:
        verbose_name_plural = 'Board members'

    def get_email_list(self):
        emails = []
        for field in self._meta.get_fields():
            if not field.primary_key:
                # We assume the first email is the one to be used
                emails.append(getattr(self, field.name).emails.first().email)
        return emails


class BoardTerm(models.Model):
    POSITIONS = (
        ('d1', 'Director at Large 1'),
        ('d2', 'Director at Large 2'),
        ('p', 'President'),
        ('s', 'Secretary'),
        ('t', 'Treasurer'),
        ('vp', 'Vice President')
    )

    elected_date = models.DateField()
    office = models.CharField(choices=POSITIONS, max_length=2)
    person = models.ForeignKey('Person')

    class Meta:
        ordering = ('-elected_date', 'person')

    @staticmethod
    def office_abbr(office):
        abbrs = {
            'director_at_large_1': 'd1',
            'director_at_large_2': 'd2',
            'president': 'p',
            'secretary': 's',
            'treasurer': 't',
            'vice_president': 'vp'
        }
        return abbrs[office]

    def __str__(self):
        return f'[{self.elected_date}] {self.person.full_name} ({self.get_office_display()})'


class Email(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


class LotNumber(models.Model):
    lot_number = models.CharField(blank=True, max_length=20, null=True)
    property = models.ForeignKey('Property')

    class Meta:
        ordering = ('property', 'lot_number')
        unique_together = ('lot_number', 'property')

    def __str__(self):
        return f'({self.lot_number}) {self.property}'


class MailingAddress(models.Model):
    city = models.CharField(max_length=20)
    line1 = models.CharField(max_length=50)
    line2 = models.CharField(blank=True, max_length=50, null=True)
    name = models.CharField(max_length=30, unique=True)
    state = USStateField()
    zip_code = models.CharField(max_length=10)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Mailing addresses'

    def __str__(self):
        ret = f'{self.name}: {self.line1}'
        if self.line2:
            ret += f', {self.line2}'
        ret += f', {self.city}, {self.state}, {self.zip_code}'
        return ret


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    prefix = models.CharField(blank=True, default=None, max_length=5, null=True)
    residential_property = models.ForeignKey('Property')
    suffix = models.CharField(blank=True, default=None, max_length=10, null=True)
    phone = PhoneNumberField(blank=True, help_text='Example: 000-000-0000.', region='US')
    active = models.BooleanField(default=True)
    emails = models.ManyToManyField(Email, through='PersonEmail')

    class Meta:
        ordering = ('last_name', 'first_name')

    def add_prefix(self):
        return f'{self.prefix} ' if self.prefix else ''

    def add_suffix(self):
        if self.suffix == 'Esq':
            return f', {self.suffix}'
        else:
            return f' {self.suffix}' if self.suffix else ''

    @property
    def get_notices_email(self):
        try:
            return list(
                set(self.residential_property.notices_emails) & set(self.emails.values_list('email', flat=True))
            )[0]
        except IndexError:
            return ''

    @property
    def full_name(self):
        full_name = f'{self.prefix} ' if self.prefix else ''
        full_name += f'{self.first_name} {self.last_name}{self.add_suffix()}'

        return full_name

    @property
    def board_email(self):
        from mailing_lists.models import MailingList

        board_ml = MailingList.objects.get(mailbox__name='Board')
        # noinspection PyTypeChecker
        return (board_ml.members.all() & self.emails.all()).first()

    def __str__(self):
        return f'{self.last_name}, {self.first_name} [{self.residential_property.mailing_address(multiline=False)}]'


class PersonEmail(models.Model):
    email = models.OneToOneField(Email, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    class Meta:
        ordering = ('person', 'email')

    def __str__(self):
        return f'[{self.person.full_name}] {self.email}'


class Property(models.Model):
    comment = models.TextField(blank=True, null=True)
    house_number = models.SmallIntegerField()
    in_hh = models.BooleanField(default=True)
    outside_mailing_address = models.ForeignKey('MailingAddress', blank=True, null=True)
    property_type = models.ForeignKey('PropertyType')
    street = models.ForeignKey('Street')

    _notices_ml = None

    class Meta:
        ordering = ('street', 'house_number')
        verbose_name_plural = 'Properties'

    def get_all_active_people(self):
        return self.person_set.filter(active=True)

    def get_all_names(self):
        last_names = set([person.last_name + person.add_suffix() for person in self.get_all_active_people()])

        if len(last_names) == 1:
            # Same last name
            all_names = ' & '.join(
                [person.add_prefix() + person.first_name for person in self.get_all_active_people()]
            ) + ' ' + last_names.pop()
        else:
            # Different last names
            all_names = ' / '.join([person.full_name for person in self.get_all_active_people()])

        return all_names

    def get_notices_ml(self):
        from mailing_lists.models import MailingList

        if self._notices_ml is None:
            self._notices_ml = MailingList.objects.get(mailbox__name='Notices')

    @property
    def household_address(self):
        return self.mailing_address(include_names=True)

    def mailing_address(self, include_names=False, multiline=True):
        if multiline:
            line_end = '\n'
            pre_zip = '  '
        else:
            line_end = pre_zip = ', '

        if self.outside_mailing_address:
            if include_names:
                names = f'{self.outside_mailing_address.name} (for {self.street_address()}){line_end}'
            else:
                names = ''

            addr = f'{names}{self.outside_mailing_address.line1}{line_end}'

            if self.outside_mailing_address.line2:
                addr += f'{self.outside_mailing_address.line2}{line_end}'

            addr += (
                f'{self.outside_mailing_address.city}, {self.outside_mailing_address.state}{pre_zip}'
                f'{self.outside_mailing_address.zip_code}'
            )

            return addr
        else:
            names = (self.get_all_names() + line_end) if include_names else ''
            return f'{names}{self.street_address()}{line_end}Rochester, NY{pre_zip}14622'

    @property
    def notices_emails(self):
        self.get_notices_ml()

        emails = []
        for person in self.get_all_active_people():
            # noinspection PyTypeChecker
            email = (self._notices_ml.members.all() & person.emails.all()).first()
            if email:
                emails.append(email.email)

        return emails

    @property
    def receives_email_notices(self):
        return any(self.notices_emails)

    @property
    def receives_no_email(self):
        return sum([person.email_set.all().count() for person in self.get_all_active_people()]) == 0

    def street_address(self):
        return f'{self.house_number} {self.street}'

    def __str__(self):
        return f'{self.house_number} {self.street}'


class PropertyType(models.Model):
    property_type = models.CharField(max_length=10, unique=True)

    class Meta:
        ordering = ('property_type',)

    def __str__(self):
        return self.property_type


class Street(models.Model):
    street = models.CharField(max_length=30, unique=True)

    class Meta:
        ordering = ('street',)

    def __str__(self):
        return self.street

apps/residents/views.py
from library.views.generic import ProtectedTemplateView

from .models import Board, BoardTerm, Property, Street


class BoardMembersListView(ProtectedTemplateView):
    template_name = 'residents/board_members.html'

    def get_context_data(self, **kwargs):
        board = Board.objects.all()[0]

        context = super().get_context_data(**kwargs)
        context['is_staff'] = self.request.user.is_staff

        for position in BoardTerm.POSITIONS:
            office = position[1].lower().replace(' ', '_')
            person = getattr(board, office)

            try:
                start_year = BoardTerm.objects.filter(person=person).first().elected_date.year
            except AttributeError:
                start_year = 'N/A'

            context[office] = {'start_year': start_year, 'person': person}
        
        return context


class MainMenuView(ProtectedTemplateView):
    template_name = 'residents/main_menu.html'


class ResidentListView(ProtectedTemplateView):
    template_name = 'residents/residents.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['properties'] = Property.objects.all()
        context['by_street'] = {}

        for street in Street.objects.all():
            context['by_street'][street.street] = Property.objects.filter(street=street)

        return context

templates/residents/base.html
{% extends "base.html" %}

{% block title %}Huntington Hills {% block residents_title %}{% endblock %}{% endblock %}

{% block navbar %}{% include "_full_navbar.html" %}{% endblock %}

{% block content %}
    {% block resident_content %}{% endblock %}
{% endblock %}

templates/residents/board_members.html
{% extends "residents/base.html" %}
{% load static %}

{% block css %}
    {{ block.super }}

    <style type="text/css">
        table {
            border: 1px solid black;
            font-size: 0.8em;
            width: 100%;
        }

        td {
            border: 1px solid black;
        }

        th {
            border: 1px solid black;
            text-align: center;
        }

        td, th {
            padding: 0.25em;
        }
    </style>
{% endblock %}

{% block residents_title %}Board Members{% endblock %}
{% block header %}Board Members{% endblock %}

{% block resident_content %}
    <table style='border-collapse: collapse;'>
        <thead>
            <tr>
                <th>Position</th>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Email</th>
                {% if is_staff %}<th>Term</th>{% endif %}
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>President</td>
                <td>{{ president.person.full_name }}</td>
                <td>{{ president.person.residential_property.street_address }}</td>
                <td>{{ president.person.phone.as_national }}</td>
                <td>
                    <a href="mailto:{{ president.person.board_email }}">
                        {{ president.person.board_email }}
                    </a>
                </td>
                {% if is_staff %}
                    {% if president.start_year == "N/A" %}
                        <td style="text-align: center;">N/A</td>
                    {% else %}
                        <td>{{ president.start_year }} - {{ president.start_year|add:"2" }}</td>
                    {% endif %}
                {% endif %}
            </tr>

            <tr>
                <td>Vice President</td>
                <td>{{ vice_president.person.full_name }}</td>
                <td>{{ vice_president.person.residential_property.street_address }}</td>
                <td>{{ vice_president.person.phone.as_national }}</td>
                <td>
                    <a href="mailto:{{ vice_president.person.board_email }}">
                        {{ vice_president.person.board_email }}
                    </a>
                </td>
                {% if is_staff %}
                    {% if vice_president.start_year == "N/A" %}
                        <td style="text-align: center;">N/A</td>
                    {% else %}
                        <td>{{ vice_president.start_year }} - {{ vice_president.start_year|add:"2" }}</td>
                    {% endif %}
                {% endif %}
            </tr>

            <tr>
                <td>Treasurer</td>
                <td>{{ treasurer.person.full_name }}</td>
                <td>{{ treasurer.person.residential_property.street_address }}</td>
                <td>{{ treasurer.person.phone.as_national }}</td>
                <td>
                    <a href="mailto:{{ treasurer.person.board_email }}">
                        {{ treasurer.person.board_email }}
                    </a>
                </td>
                {% if is_staff %}
                    {% if treasurer.start_year == "N/A" %}
                        <td style="text-align: center;">N/A</td>
                    {% else %}
                        <td>{{ treasurer.start_year }} - {{ treasurer.start_year|add:"2" }}</td>
                    {% endif %}
                {% endif %}
            </tr>

            <tr>
                <td>Secretary</td>
                <td>{{ secretary.person.full_name }}</td>
                <td>{{ secretary.person.residential_property.street_address }}</td>
                <td>{{ secretary.person.phone.as_national }}</td>
                <td>
                    <a href="mailto:{{ secretary.person.board_email }}">
                        {{ secretary.person.board_email }}
                    </a>
                </td>
                {% if is_staff %}
                    {% if secretary.start_year == "N/A" %}
                        <td style="text-align: center;">N/A</td>
                    {% else %}
                        <td>{{ secretary.start_year }} - {{ secretary.start_year|add:"2" }}</td>
                    {% endif %}
                {% endif %}
            </tr>

            <tr>
                <td>Director At Large</td>
                <td>{{ director_at_large_1.person.full_name }}</td>
                <td>{{ director_at_large_1.person.residential_property.street_address }}</td>
                <td>{{ director_at_large_1.person.phone.as_national }}</td>
                <td>
                    <a href="mailto:{{ director_at_large_1.person.board_email }}">
                        {{ director_at_large_1.person.board_email }}
                    </a>
                </td>
                {% if is_staff %}
                    {% if director_at_large_1.start_year == "N/A" %}
                        <td style="text-align: center;">N/A</td>
                    {% else %}
                        <td>
                            {{ director_at_large_1.start_year }} - {{ director_at_large_1.start_year|add:"2" }}
                        </td>
                    {% endif %}
                {% endif %}
            </tr>

            <tr>
                <td>Director At Large</td>
                <td>{{ director_at_large_2.person.full_name }}</td>
                <td>{{ director_at_large_2.person.residential_property.street_address }}</td>
                <td>{{ director_at_large_2.person.phone.as_national }}</td>
                <td>
                    <a href="mailto:{{ director_at_large_2.person.board_email }}">
                        {{ director_at_large_2.person.board_email }}
                    </a>
                </td>
                {% if is_staff %}
                    {% if director_at_large_2.start_year == "N/A" %}
                        <td style="text-align: center;">N/A</td>
                    {% else %}
                        <td>
                            {{ director_at_large_2.start_year }} - {{ director_at_large_2.start_year|add:"2" }}
                        </td>
                    {% endif %}
                {% endif %}
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/residents/main_menu.html
{% extends "residents/base.html" %}
{% load auth %}
{% load static %}

{% block css %}
    {{ block.super }}

    <style type="text/css">
        .arrow_bullet {
            list-style: none;
            position: relative;
        }

        .arrow_bullet li::before {
            content: '⮕';
            left: 2em;
            position: absolute;
        }

        fieldset {
            height: 90%;
            margin-bottom: 1em;
        }
    </style>
{% endblock %}

{% block residents_title %}Residents Main Menu{% endblock %}
{% block header %}Residents Main Menu{% endblock %}

{% block navbar %}{% include "_full_navbar.html" %}{% endblock %}

{% block resident_content %}
    <p>Your choices:</p>

    <ul class="arrow_bullet">
        <li><a href="{% url 'resident:board' %}">Board Members</a></li>
        <li><a href="{% url 'resident:information' %}">Residents List</a></li>
    </ul>

    {% if request.user.is_staff or request.user|in_group:"Bow Hunt" %}
        <fieldset>
            <legend>Bow Hunt</legend>

            <ul class="arrow_bullet">
                <li><a href="{% url 'bow_hunt:log_sheet' %}">View Daily Log Sheets (IPD and Non IPD)</a></li>
                <li><a href="{% url 'bow_hunt:hunter_analysis' %}">View Hunter Analysis</a></li>
                <li>
                    <a href="{% url 'bow_hunt:location_analysis' %}">View Location Analysis</a>
                    (properties as listed in the IPD Daily Bow Hunt Logs)
                </li>
                <li>
                    <a href="{% url 'bow_hunt:site_analysis' %}">View Site Analysis</a>
                    (physical properties that one or more <em>locations</em> can map to)
                </li>
            </ul>
        </fieldset>
    {% endif %}
{% endblock %}

templates/residents/residents.html
{% extends "residents/base.html" %}

{% block css %}
    {{ block.super }}

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.21/fh-3.1.7/datatables.min.css"/>

    <style>
        caption {
            font-weight: bold;
            margin-bottom: 0.5em;
        }

        #bystreet_div table {
            margin-bottom: 3em;
        }

        th {
            text-align: center;
        }
    </style>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.21/fh-3.1.7/datatables.min.js"></script>

    <script type='text/javascript'>
        $(document).ready(function() {
            $("#byname_div table").DataTable({
                fixedHeader: {
                    header: true
                },
                ordering: false,
                paging: false
            });

            $("#bystreet_div table").DataTable({
                bInfo: false,
                fixedHeader: {
                    header: true
                },
                ordering: false,
                paging: false,
                searching: false
            })
        });

        function byName()
        {
            let name_button = document.getElementById("byname_button");
            let street_button = document.getElementById("bystreet_button");
        
            let name_div = document.getElementById("byname_div");
            let street_div = document.getElementById("bystreet_div");
        
            name_div.style.display = "";
            street_div.style.display = "none";
        
            name_button.disabled = true;
            street_button.disabled = false;
        }
        
        function byStreet()
        {
            let name_button = document.getElementById("byname_button");
            let street_button = document.getElementById("bystreet_button");
        
            let name_div = document.getElementById("byname_div");
            let street_div = document.getElementById("bystreet_div");
        
            name_div.style.display = "none";
            street_div.style.display = "";
        
            name_button.disabled = false;
            street_button.disabled = true;
        }
    </script>
{% endblock %}

{% block residents_title %}Resident Information{% endblock %}
{% block header %}Resident Information{% endblock %}

{% block resident_content %}
    <div style="margin-bottom: 2em; text-align: center;">
        <input type="button"  name="Group By Name" value="Group By Name" onclick="byName();"
               disabled="disabled" id="byname_button" />

        <input type="button"  name="Group By Street" value="Group By Street"
               onclick="byStreet();" id="bystreet_button" />
    </div>

    <div id="byname_div">
        <table class="display" style="width: 100%;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Email</th>
                </tr>
            </thead>

            <tbody>
                {% for property in properties %}
                    <tr>
                        <td>
                            {% for person in property.get_all_active_people %}
                                {{ person.full_name }} <br />
                            {% endfor %}
                        </td>

                        <td>{{ property.street_address }}</td>

                        <td>
                             {% for person in property.get_all_active_people %}
                                {% for email in person.emails.all %}
                                    {{ email }}<br />
                                {% endfor %}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div id="bystreet_div" style="display: none;">
        {% for street, property_list in by_street.items %}
            <table class="display" style="width: 100%;">
                <caption>{{ street }}</caption>

                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Email</th>
                    </tr>
                </thead>

                <tbody>
                    {% for property in property_list %}
                        <tr>
                            <td>
                                {% for person in property.get_all_active_people %}
                                    {{ person.full_name }} <br />
                                {% endfor %}
                            </td>

                            <td>{{ property.street_address }}</td>

                            <td>
                                 {% for person in property.get_all_active_people %}
                                    {% for email in person.emails.all %}
                                        {{ email }}<br />
                                    {% endfor %}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endfor %}
    </div>
{% endblock %}