apps/bow_hunt/urls.py
from django.conf.urls import url

from .add import AddIPDFinalReport, AddLogs, AddNonIPDLogs, FetchLogSheetData
from .commons import CommonsHunting
from .daily_log_sheets import FetchLogSheetsByYear, LogSheetView
from .analysis import HunterAnalysis, LocationAnalysis, SiteAnalysis

app_name = 'bow_hunt'
urlpatterns = [
    url(r'^analysis/by_hunter/$', HunterAnalysis.as_view(), name='hunter_analysis'),
    url(r'^analysis/by_location/$', LocationAnalysis.as_view(), name='location_analysis'),
    url(r'^analysis/by_site/$', SiteAnalysis.as_view(), name='site_analysis'),
    url(r'^commons/$', CommonsHunting.as_view(), name='commons_hunting'),
    url(r'^log_sheet/$', LogSheetView.as_view(), name='log_sheet'),
    url(r'^log_sheet/add/ipd_final_report/$', AddIPDFinalReport.as_view(), name='add_ipd_final_report'),
    url(r'^log_sheet/add/logs/$', AddLogs.as_view(), name='add_logs'),
    url(r'^log_sheet/add/non_ipd_logs/$', AddNonIPDLogs.as_view(), name='add_non_ipd_logs'),
    url(r'^log_sheet/fetch/by_year/locations/$', FetchLogSheetData.as_view(), name='fetch_log_sheet_data'),
    url(r'^log_sheet/fetch/by_year/log_sheets/$', FetchLogSheetsByYear.as_view(), name='fetch_log_sheet_by_year')
]

apps/mailing_lists/urls.py
from django.conf.urls import url

from library.views.generic import ProtectedTemplateView

from .archives import Archives, ArchiveList
from .by import ByAuthor, ByDate, BySubject, ByThread
from .message import MessageDetailView


app_name = 'mailing_lists'
urlpatterns = [
    url(r'^archives/(?P<ml_name_slug>[-\w]+)$', Archives.as_view(), name='archives'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/byauthor/(?P<archive>[\w ]+)$', ByAuthor.as_view(), name='by_author'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/bydate/(?P<archive>[\w ]+)$', ByDate.as_view(), name='by_date'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/bysubject/(?P<archive>[\w ]+)$', BySubject.as_view(), name='by_subject'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/bythread/(?P<archive>[\w ]+)$', ByThread.as_view(), name='by_thread'),
    url(r'^archives/list/$', ArchiveList.as_view(), name='archive_list'),
    url(r'^archives/message/(?P<pk>[\d]+)/$', MessageDetailView.as_view(), name='message'),
    url(
        r'^lists/$',
        ProtectedTemplateView.as_view(template_name='mailing_lists/lists.html'),
        name='lists'
    ),
]

apps/news/urls.py
from django.conf.urls import url

from .views import Archived, ArticleRedirect, ByYear, CurrentArticles

app_name = 'news'
urlpatterns = [
    url(r'^archived/$', Archived.as_view(), name='archived'),
    url(r'^article/(?P<pk>\d+)$', ArticleRedirect.as_view(), name='article_redirect'),
    url(r'^by_year/(?P<year>\d{4})/$', ByYear.as_view(), name='by_year'),
    url(r'^by_year/(?P<year>\d{4})/(?P<slug>[\w-]+)$', ByYear.as_view(), name='by_year'),
    url(r'^current/$', CurrentArticles.as_view(), name='current_news_articles')
]

apps/residents/urls.py
from django.conf.urls import url

from .views import BoardMembersListView, MainMenuView, ResidentListView

app_name = 'resident'
urlpatterns = [
    url(r'^board_members/$', BoardMembersListView.as_view(), name='board'),
    url(r'^information/$', ResidentListView.as_view(), name='information'),
    url(r'^main_menu/$', MainMenuView.as_view(), name='main_menu')
]

apps/staff/urls.py
from django.conf.urls import url

from .views import (
    AllCurrentNews, AllDataView, EmailNoticeList, MailingAddresses, MainMenuView, NonEmailNoticeList, SignInSheet,
    UpdateBoardMembers, UpdateHomeowners
)


app_name = 'staff'
urlpatterns = [
    url(r'^all_current_news/$', AllCurrentNews.as_view(), name='all_current_news'),
    url(r'^all_data/$', AllDataView.as_view(), name='all_data'),
    url(r'^download/email_notice_list/$', EmailNoticeList.as_view(), name='email_notice_list'),
    url(r'^download/non_email_notice_list/$', NonEmailNoticeList.as_view(), name='non_email_notice_list'),
    url(r'^download/sign_in_sheet/$', SignInSheet.as_view(), name='sign_in_sheet'),
    url(r'^mailing_addresses/$', MailingAddresses.as_view(), name='mailing_addresses'),
    url(r'^main_menu/$', MainMenuView.as_view(), name='main_menu'),
    url(r'^update_board_members/(?P<pk>\d+)$', UpdateBoardMembers.as_view(), name='update_board_members'),
    url(r'^update_homeowners/$', UpdateHomeowners.as_view(), name='update_homeowners')
]

hh/urls.py
"""hh URL Configuration
"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView

from library.views.generic import ProtectedMedia

urlpatterns = ([
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authentication.urls')),
    url(r'^bow_hunt/', include('bow_hunt.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^history/', include('history.urls')),
    url(r'^mailing_lists/', include('mailing_lists.urls')),
    url(r'^media/members/(?:.*)$', ProtectedMedia.as_view(), name='media'),
    url(r'^news/', include('news.urls')),
    url(r'^resident/', include('residents.urls')),
    url(r'^search/$', TemplateView.as_view(template_name='search.html'), name='search'),
    url(r'^staff/', include('staff.urls')),
    url(r'^technical/$', TemplateView.as_view(template_name='technical.html'), name='technical'),
    url(r'^tinymce/', include('tinymce.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

apps/staff/forms.py
from datetime import date

from django import forms

from library.forms.forms import RequiredFormSet

from residents.models import Board, Person


class UpdateBoardMembersForm(forms.ModelForm):
    elected_date = forms.DateField(initial=date.today)

    class Meta:
        # We list all the fields so that we can specify the order in which they appear on the page
        fields = ['president', 'vice_president', 'treasurer', 'secretary', 'director_at_large_1', 'director_at_large_2']
        model = Board


class UpdateHomeownersForm(forms.ModelForm):
    class Meta:
        fields = ('prefix', 'first_name', 'last_name', 'suffix', 'phone')
        model = Person


UpdateHomeownersFormSet = forms.models.modelformset_factory(
    Person, extra=2, form=UpdateHomeownersForm, formset=RequiredFormSet
)

apps/staff/views.py
from easy_pdf.views import PDFTemplateView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages import success
from django.views.generic import FormView, TemplateView, UpdateView
from django.urls import reverse_lazy

from .forms import UpdateBoardMembersForm, UpdateHomeownersFormSet

from library.contrib.auth.mixins import IsStaffMixin
from library.views.generic.csv import CSVFileView

from mailing_lists.models import MailingList

from news.views import CurrentArticles

from residents.models import Board, BoardTerm, Person, Property, Street


class AllCurrentNews(CurrentArticles):
    template_name = 'staff/all_current_news.html'


class AllDataView(LoginRequiredMixin, IsStaffMixin, TemplateView):
    template_name = 'staff/all_data.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['properties'] = Property.objects.all()
        context['emails'] = {}

        for residential_property in context['properties']:
            context['emails'][residential_property.id] = {}
            for person in residential_property.get_all_active_people().order_by('first_name'):
                context['emails'][residential_property.id][person] = person.emails.values_list('email', flat=True)

        return context


class EmailNoticeList(LoginRequiredMixin, IsStaffMixin, CSVFileView):
    csv_filename = 'email_notice_list.csv'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['data'] = [['', 'Names', 'Address', 'Emails'], []]

        notices_ml = MailingList.objects.get(mailbox__name='Notices')

        for street in Street.objects.all():
            context['data'].append([street.street])

            for residential_property in Property.objects.filter(street=street):
                emails = []
                people = []

                for person in residential_property.get_all_active_people():
                    notice_email = (notices_ml.members.all() & person.emails.all()).first()
                    if notice_email:
                        emails.append(notice_email.email)
                        people.append(person.full_name)

                if people:
                    context['data'].append(
                        ['', '\n'.join(people), residential_property.street_address(), '\n'.join(emails)]
                    )

            context['data'].append([])

        return context


class MailingAddresses(LoginRequiredMixin, IsStaffMixin, TemplateView):
    template_name = 'staff/mailing_addresses.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['properties'] = Property.objects.all()
        return context


class MainMenuView(LoginRequiredMixin, IsStaffMixin, TemplateView):
    template_name = 'staff/main_menu.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_main_menu'] = True
        return context


class NonEmailNoticeList(LoginRequiredMixin, IsStaffMixin, CSVFileView):
    csv_filename = 'non_email_notice_list.csv'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['data'] = []

        for street in Street.objects.all():
            context['data'].append([street.street])

            for residential_property in Property.objects.filter(street=street):
                if not residential_property.receives_email_notices:
                    context['data'].append(['', residential_property.mailing_address(include_names=True)])

            context['data'].append([])

        return context


class SignInSheet(LoginRequiredMixin, IsStaffMixin, PDFTemplateView):
    pdf_filename = 'sign_in_sheet.pdf'
    template_name = 'staff/annual_meeting_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(
            pagesize='letter',
            title='Attendees Sign In Sheet',
            **kwargs
        )
        context['properties'] = Property.objects.all()

        return context


class UpdateBoardMembers(LoginRequiredMixin, IsStaffMixin, UpdateView):
    # We list all the fields so that we can specify the order in which they appear on the page
    # fields = ['president', 'vice_president', 'treasurer', 'secretary', 'director_at_large_1', 'director_at_large_2']
    form_class = UpdateBoardMembersForm
    model = Board
    success_url = reverse_lazy('resident:board')
    template_name = 'staff/update_board_members.html'

    def form_valid(self, form):
        elected_date = form.cleaned_data['elected_date']

        for position, person in form.cleaned_data.items():
            if position != 'elected_date':
                BoardTerm.objects.create(
                    elected_date=elected_date,
                    office=BoardTerm.office_abbr(position),
                    person=person
                )

        return super().form_valid(form)


class UpdateHomeowners(LoginRequiredMixin, IsStaffMixin, FormView):
    form_class = UpdateHomeownersFormSet
    success_url = reverse_lazy('staff:update_homeowners')
    template_name = 'staff/update_homeowners.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['properties_by_street'] = {}

        for street in Street.objects.all():
            context['properties_by_street'][street.street] = Property.objects.filter(street=street)

        return context

    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the form.
        """
        kwargs = {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'queryset': Person.objects.none(),
            'unrequired': [1]
        }

        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form):
        residential_property = Property.objects.get(id=self.request.POST['property'])

        # Deactivate the old property owners
        Person.objects.filter(residential_property=residential_property).update(active=False)

        for person_form in form.forms:
            if person_form.cleaned_data:
                # Add the new property owners
                person = person_form.save(commit=False)
                person.residential_property = residential_property
                person.save()

        success(self.request, 'Updated Homeowners')

        return super().form_valid(form)

templates/staff/all_current_news.html
{% extends "staff/base.html" %}

{% block staff_title %}View All Current News Articles{% endblock %}
{% block header %}View All Current News Articles{% endblock %}

{% block staff_content %}
    {% include "news/current_articles.html" %}
{% endblock %}

templates/staff/all_data.html
{% extends "staff/base.html" %}
{% load lookup %}

{% block css %}
    {{ block.super }}

    <style>
        caption {
            font-weight: bold;
            margin-bottom: 1em;
        }

        hr {
            margin-bottom: 1.5em;
            margin-top: 1.5em;
        }

        .row_label {
            text-align: left;
            vertical-align: top;
            width: 25%;
        }

        table {
            border-collapse: separate;
            border-spacing: 0 0.5em;
            width: 100%;
        }

        tr {
            margin-bottom: 5em;
        }

        ul {
            margin-top: 0.25em;
        }
    </style>
{% endblock %}

{% block staff_title %}View All Data{% endblock %}
{% block header %}View All Data{% endblock %}

{% block staff_content %}
    {% for property in properties %}
        <table>
            <caption>{{ property.street_address }}</caption>

            <tbody>
                <tr>
                    <td class="row_label">People:</td>
                    <td>
                        {% for person in property.get_all_active_people %}
                            {{ person.full_name }} <br />
                        {% endfor %}
                    </td>
                </tr>

                <tr>
                    <td class="row_label">Mailing Address:</td>
                    <td>{{ property.mailing_address|linebreaksbr }}</td>
                </tr>

                <tr>
                    <td class="row_label">Emails:</td>
                    <td>
                        {% with property_emails=emails|dict_lookup:property.id %}
                            {% for person, emails in property_emails.items %}
                                {% if emails %}
                                    <div style="font-size: 95%;">{{ person.first_name }}:</div>

                                    <ul style="list-style: none;">
                                        {% for email in emails %}
                                            <li>
                                                <a href="mailto:{{ email }}">{{ email }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    </td>
                </tr>

                <tr>
                    <td class="row_label">In HH:</td>
                    <td>{{ property.in_hh|yesno }}</td>
                </tr>

                <tr>
                    <td class="row_label">Type:</td>
                    <td>{{ property.property_type }}</td>
                </tr>

                <tr>
                    <td class="row_label">Lot Numbers:</td>
                    <td>
                        {% for lot_number in property.lotnumber_set.all %}
                            {{ lot_number.lot_number }}<br />
                        {% endfor %}
                    </td>
                </tr>

                <tr>
                    <td class="row_label">Comments:</td>
                    <td>{{ property.comment }}</td>
                </tr>
            </tbody>
        </table>

        {% if not forloop.last %}
            <hr />
        {% endif %}
    {% endfor %}
{% endblock %}

templates/staff/annual_meeting_list.html
{% extends "easy_pdf/base.html" %}

{% block style_base %}
    {{ block.super }}

    <style type="text/css">
        .counter {
            vertical-align: top;
            width: 20px;
        }

        .member {
            width: 140px;
        }

        .street_address {
            width: 130px;
        }

        tr {
            padding-top: 0.5em;
        }

        tr td {
            border-bottom: 1px solid #000;
        }

        tr td:first-child {
            border-bottom: inherit;
        }
    </style>
{% endblock %}

{% block page_header %}
    <h1 style="text-align: center;">Huntington Hills Annual Meeting<br />Attendees Sign In Sheet</h1>
{% endblock %}

{% block content %}
    <table style='border-collapse: collapse;'>
        <thead>
            <tr>
                <th></th>
                <th>Member</th>
                <th>Address</th>
                <th>Email</th>
                <th style="padding: 1.5em;">Email<br />Notice</th>
                <th>Signature</th>
            </tr>
        </thead>

        <tbody>
            {% for property in properties %}
                <tr>
                    <td class="counter">{{ forloop.counter }}.</td>

                    <td class="member">
                        {% for person in property.get_all_active_people %}
                            {{ person.full_name }}<br />
                        {% endfor %}
                    </td>

                    <td class="street_address">{{ property.street_address}}</td>

                    <td>
                        {% for person in property.get_all_active_people %}
                            {{ person.get_notices_email }}
                        {% endfor %}
                    </td>

                    <td style="text-align: center;">
                        {% if property.receives_email_notices %}
                            [&#10004;]
                        {% else %}
                            [&nbsp;&nbsp;&nbsp;]
                        {% endif %}
                    </td>

                    <td></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/staff/base.html
{% extends "base.html" %}
{% load static %}

{% block title %}HH Admin: {% block staff_title %}{% endblock %}{% endblock %}

{% block navbar %}{% include "_full_navbar.html" %}{% endblock %}

{% block content %}
    <div id="links_div">
        <div class="links">
            {% if is_main_menu %}
                [<span>Main Menu</span> | <a href="{% url 'admin:index' %}">Admin</a>]
            {% else %}
                [<a href="{% url 'staff:main_menu' %}">Main Menu</a> | <a href="{% url 'admin:index' %}">Admin</a>]
            {% endif %}
        </div>
    </div>

    {% block staff_content %}{% endblock %}
{% endblock %}

templates/staff/mailing_addresses.html
{% extends "staff/base.html" %}

{% block js %}
    <script type='text/javascript'>
        function byAll()
        {
            let all_button = document.getElementById("byall_button");
            let noemail_button = document.getElementById("bynoemail_button");
        
            let all_div = document.getElementById("byall_div");
            let noemail_div = document.getElementById("bynoemail_div");
        
            all_div.style.display = "";
            noemail_div.style.display = "none";
        
            all_button.disabled = true;
            noemail_button.disabled = false;
        }
        
        function byNoEmail()
        {
            let all_button = document.getElementById("byall_button");
            let noemail_button = document.getElementById("bynoemail_button");
        
            let all_div = document.getElementById("byall_div");
            let noemail_div = document.getElementById("bynoemail_div");
        
            all_div.style.display = "none";
            noemail_div.style.display = "";
        
            all_button.disabled = false;
            noemail_button.disabled = true;
        }
        </script>
{% endblock %}

{% block staff_title %}Mailing Addresses{% endblock %}
{% block header %}Mailing Addresses{% endblock %}

{% block staff_content %}
    <div style="margin-bottom: 2em; text-align: center;">
        <input type="button"  name="All Households" value="All Households" onclick="byAll();"
               disabled="disabled" id="byall_button" />

        <input type="button"  name="Households With No Email" value="Households With No Email"
               onclick="byNoEmail();" id="bynoemail_button" />
    </div>

    <div id="byall_div">
        {% for property in properties %}
            {{ property.household_address|linebreaksbr }}<br style="margin-bottom: 1em;" />
        {% endfor %}
    </div>

    <div id="bynoemail_div" style="display: none;">
        {% for property in properties %}
            {% if property.receives_no_email %}
                {{ property.household_address|linebreaksbr }}<br style="margin-bottom: 1em;" />
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/staff/main_menu.html
{% extends "staff/base.html" %}
{% load static %}

{% block css %}
    {{ block.super }}

    <style type="text/css">
        .arrow_bullet {
            list-style: none;
            position: relative;
        }

        .arrow_bullet li::before {
            content: '⮕';
            left: 2em;
            position: absolute;
        }

        fieldset {
            height: 90%;
            margin-bottom: 1em;
        }
    </style>
{% endblock %}

{% block staff_title %}Main Menu{% endblock %}
{% block header %}Staff Main Menu{% endblock %}

{% block navbar %}{% include "_full_navbar.html" %}{% endblock %}

{% block staff_content %}
    <div>

        <fieldset>
            <legend>Action</legend>

            <ul class="arrow_bullet">
                <li><a href="{% url 'staff:update_board_members' 1 %}">Update Board Members</a></li>
                <li><a href="{% url 'staff:update_homeowners' %}">Update Homeowners</a></li>
            </ul>

        </fieldset>

        <fieldset>
            <legend>Bow Hunt</legend>

            <ul class="arrow_bullet">
                <li><a href="{% url 'bow_hunt:add_ipd_final_report' %}">Add IPD Final Report</a></li>
                <li><a href="{% url 'bow_hunt:add_logs' %}">Add IPD Logs</a></li>
                <li style="padding-bottom: 2em;">
                    <a href="{% url 'bow_hunt:add_non_ipd_logs' %}">Add Non IPD Logs</a>
                </li>
                <li><a href="{% url 'bow_hunt:log_sheet' %}">Daily Log Sheets (IPD and Non IPD)</a></li>
                <li><a href="{% url 'bow_hunt:hunter_analysis' %}">Hunter Analysis</a></li>
                <li><a href="{% url 'bow_hunt:location_analysis' %}">Location Analysis</a></li>
                <li style="padding-bottom: 2em;"><a href="{% url 'bow_hunt:site_analysis' %}">Site Analysis</a></li>
                <li><a href="{% url 'bow_hunt:commons_hunting' %}">Hunting on the Commons</a></li>
            </ul>
        </fieldset>

        <fieldset>
            <legend>Download</legend>

            <ul class="arrow_bullet">
                <li><a href="{% url 'staff:sign_in_sheet' %}">Annual Meeting List (PDF format)</a></li>
                <li><a href="{% url 'staff:email_notice_list' %}">Email Notice List (CSV format)</a></li>
                <li><a href="{% url 'staff:non_email_notice_list' %}">Non Email Notice List (CSV format)</a></li>
            </ul>
        </fieldset>

        <fieldset>
            <legend>View</legend>

            <ul class="arrow_bullet">
                <li><a href="{% url 'staff:all_current_news' %}">All Current News</a></li>
                <li><a href="{% url 'staff:all_data' %}">All Data</a></li>
                <li><a href="{% url 'news:archived' %}">Archived News</a></li>
                <li><a href="{% url 'resident:board' %}">Board Members</a></li>
                <li><a href="{% url 'staff:mailing_addresses' %}">Mailing Addresses</a></li>
                <li><a href="{% url 'mailing_lists:archive_list' %}">Mailing List Archives</a></li>
                <li><a href="{% url 'resident:information' %}">Residents List</a></li>
            </ul>
        </fieldset>
    </div>
{% endblock %}

templates/staff/staff_base.html
{% extends "base.html" %}
{% load static %}

{% block title %}HH Admin: {% block staff_title %}{% endblock %}{% endblock %}

{% block navbar %}{% include "_full_navbar.html" %}{% endblock %}

{% block content %}
    <div id="links_div">
        <div class="links">
            {% if is_main_menu %}
                [<span>Main Menu</span> | <a href="{% url 'admin:index' %}">Admin</a>]
            {% else %}
                [<a href="{% url 'staff:main_menu' %}">Main Menu</a> | <a href="{% url 'admin:index' %}">Admin</a>]
            {% endif %}
        </div>
    </div>

    {% block staff_content %}{% endblock %}
{% endblock %}

templates/staff/update_board_members.html
{% extends "staff/base.html" %}
{% load static %}

{% block css %}
    {{ block.super }}

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" />

    <style type="text/css">
        button {
            cursor: not-allowed;
        }

        .ui-datepicker-trigger {
            cursor: pointer;
            padding-left: 0.75em;
        }
    </style>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="//code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <script type='text/javascript'>
        $(document).ready(function() {
            let idElectedDate = $("#id_elected_date");

            idElectedDate.datepicker({
                buttonImage: "{% static 'img/calendar.gif' %}",
                buttonImageOnly: true,
                buttonText: "Select date",
                onSelect: function(dateText, inst) {
                    if (dateText !== inst.lastVal) {
                        $(this).change();
                    }
                },
                showOn: "button"
            }).datepicker("setDate", new Date());

            $("button").prop("disabled", true);

            idElectedDate.add("select").change(function() {
                $("button").prop("disabled", false).css("cursor", "pointer");
            });
        });
    </script>
{% endblock %}

{% block staff_title %}Update Board Members{% endblock %}
{% block header %}Update Board Members{% endblock %}

{% block staff_content %}
    <form action="" method="post">
        {%  csrf_token %}

        <p>
            New records will be created for all individuals for the current term.
        </p>

        {{ form.as_p }}

        <div style="margin-top: 2em;"><button type="submit">Update</button></div>
    </form>
{% endblock %}

templates/staff/update_homeowners.html
{% extends "staff/base.html" %}

{% block css %}
    {{ block.super }}

    <style type="text/css">
        caption {
            font-weight: bold;
            margin-bottom: 0.25em;
        }

        label {
            font-weight: normal;
        }
    </style>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.21/fh-3.1.7/datatables.min.js"></script>

    <script type='text/javascript'>
        $(document).ready(function() {
            $("#property_select").change(function() {
                $("#person").prop("disabled", !$(this).find("option:selected").val().length);
            });
        });
    </script>
{% endblock %}

{% block staff_title %}Update Homeowners{% endblock %}
{% block header %}Update Homeowners{% endblock %}

{% block staff_content %}
    <p style="margin-bottom: 2em;">
        Choose a property and then add the primary homeowner name.
    </p>

    <form method="post">
        {% csrf_token %}

        <div style="margin-bottom: 2em;">
            <label>Property:
                <select id="property_select" name="property">
                    <option value="">----------</option>

                    {% for street, property_list in properties_by_street.items %}
                        <optgroup label="{{ street }}">
                            {% for property in property_list %}
                                <option value="{{ property.id }}">{{ property }}</option>
                            {% endfor %}
                        </optgroup>
                    {% endfor %}
                </select>
            </label>
        </div>

        <fieldset id="person" style="border: 0; margin: 0; padding: 0;" disabled>
            {{ form.management_form }}

            {% for person_form in form.forms %}
                <table style="margin-bottom: 2em;">
                    <caption>Person {{ forloop.counter }}</caption>
                    {{ person_form.as_table }}
                </table>
            {% endfor %}

            <div style="text-align: center;">
                <input type="submit" value="Update">
            </div>
        </fieldset>
    </form>
{% endblock %}