apps/contact/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import ContactFormView


app_name = 'contact'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='contact/contact.html'), name='contact'),
    url(r'^adam/$', ContactFormView.as_view(), {'recipient': 'Adam Stein'}, name='adam'),
    url(r'^board/$', ContactFormView.as_view(), {'recipient': 'Board'}, name='board'),
    url(r'^webmaster/$', ContactFormView.as_view(), {'recipient': 'Webmaster'}, name='webmaster')
]

apps/mailing_lists/urls.py
from django.conf.urls import url

from library.views.generic import ProtectedTemplateView

from .archives import Archives, ArchiveList
from .by import ByAuthor, ByDate, BySubject, ByThread
from .message import MessageDetailView


app_name = 'mailing_lists'
urlpatterns = [
    url(r'^archives/(?P<ml_name_slug>[-\w]+)$', Archives.as_view(), name='archives'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/byauthor/(?P<archive>[\w ]+)$', ByAuthor.as_view(), name='by_author'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/bydate/(?P<archive>[\w ]+)$', ByDate.as_view(), name='by_date'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/bysubject/(?P<archive>[\w ]+)$', BySubject.as_view(), name='by_subject'),
    url(r'^archives/(?P<ml_name_slug>[-\w]+)/bythread/(?P<archive>[\w ]+)$', ByThread.as_view(), name='by_thread'),
    url(r'^archives/list/$', ArchiveList.as_view(), name='archive_list'),
    url(r'^archives/message/(?P<pk>[\d]+)/$', MessageDetailView.as_view(), name='message'),
    url(
        r'^lists/$',
        ProtectedTemplateView.as_view(template_name='mailing_lists/lists.html'),
        name='lists'
    ),
]

hh/urls.py
"""hh URL Configuration
"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView

from library.views.generic import ProtectedMedia

urlpatterns = ([
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authentication.urls')),
    url(r'^bow_hunt/', include('bow_hunt.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^history/', include('history.urls')),
    url(r'^mailing_lists/', include('mailing_lists.urls')),
    url(r'^media/members/(?:.*)$', ProtectedMedia.as_view(), name='media'),
    url(r'^news/', include('news.urls')),
    url(r'^resident/', include('residents.urls')),
    url(r'^search/$', TemplateView.as_view(template_name='search.html'), name='search'),
    url(r'^staff/', include('staff.urls')),
    url(r'^technical/$', TemplateView.as_view(template_name='technical.html'), name='technical'),
    url(r'^tinymce/', include('tinymce.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

apps/mailing_lists/models.py
import logging
import re
from smtplib import SMTPSenderRefused

from django.conf import settings
from django.core.mail import BadHeaderError, EmailMessage, EmailMultiAlternatives, get_connection
from django.db import models
from django.dispatch import receiver
from django.shortcuts import reverse
from django.template.defaultfilters import pluralize
from django.utils.text import slugify

import upsilonconf

from lxml.html.clean import Cleaner, autolink_html

from django_mailbox.models import Mailbox, Message
from django_mailbox.signals import message_received

from residents.models import Email

logger = logging.getLogger(__name__)


# We use the same cleaner for every message with HTML, so only create this once
cleaner = Cleaner(
    add_nofollow=False,
    annoying_tags=True,
    comments=True,
    embedded=True,
    forms=True,
    frames=True,
    javascript=True,
    page_structure=False,
    processing_instructions=True,
    remove_unknown_tags=True,
    safe_attrs_only=True,
    scripts=True
)


class MailingList(models.Model):
    allow_anonymous_posts = models.BooleanField(default=False)
    can_post = models.ManyToManyField(Email, blank=True, related_name='can_post')    # If empty, all members can post
    email = models.EmailField()
    mailbox = models.OneToOneField(Mailbox)
    members = models.ManyToManyField(Email, related_name='members')
    name_slug = models.SlugField()

    class Meta:
        ordering = ('mailbox__name',)

    @property
    def bounce_email(self):
        pieces = self.email.split('@')
        return f'{pieces[0]}-bounces@{pieces[1]}'

    def member(self, email):
        try:
            return self.members.get(email=email).personemail.person
        except Email.DoesNotExist:
            return None

    def member_can_post(self, email):
        return self.can_post.count() == 0 or self.can_post.filter(email=email).exists()

    @property
    def owner_email(self):
        pieces = self.email.split('@')
        return f'{pieces[0]}-owner@{pieces[1]}'

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.mailbox.name)
        super().save(*args, **kwargs)

    def __str__(self):
        num_members = self.members.count()
        num_can_post = self.can_post.count()
        if self.allow_anonymous_posts:
            can_post = 'anonymous posts allowed'
        elif num_can_post == 0:
            can_post = 'all members can post'
        else:
            can_post = f'{num_can_post} member{pluralize(num_can_post)} can post'
        return f'{self.mailbox.name} ({num_members} member{pluralize(num_members)}, {can_post})'


class RejectedMessage(models.Model):
    message = models.OneToOneField(Message, on_delete=models.CASCADE)

    def __str__(self):
        return self.message.subject


@receiver(message_received)
def send(sender, message, **_):
    try:
        mailing_list = sender.mailinglist
    except AttributeError:
        # Probably a re-send of the message received signal in Django Admin, can ignore
        pass
    else:
        email_object = message.get_email_object()

        if email_object.get('X-Hh-Beenthere') == mailing_list.email:
            # This was the message that was sent out, don't need to store the one sent back to the ML
            message.delete()
        else:
            member = mailing_list.member(message.from_address[0])

            # We allow posting to this mailing list if:
            #
            #   1) the sender is not in the system at all and the ML allows anonymous posts
            #   2) the sender is a member of this ML and there is no can_post list (all and only members can post)
            #   3) the sender is on the can_post list
            if member:
                can_post = mailing_list.member_can_post(message.from_address[0])
            else:
                can_post = mailing_list.allow_anonymous_posts


            config = upsilonconf.load('.env.json')['Mailing Lists']

            connection_args = {
                'host': config.host,
                'password': config.password,
                'port': config.port,
                'use_tls': True,
                'username': config.username
            }

            if can_post:
                if member:
                    from_email = f'{member.full_name} via {sender.name} <{mailing_list.email}>'
                else:
                    from_email = f'{message.from_header} via {sender.name} <{mailing_list.email}>'

                # Remove any [ML NAME], Re: strings, and newlines
                subject = (
                    re.sub(r'(?<!^)(?i)Re: ', '', message.subject.replace(f'[{sender.name}] ', ''), flags=re.M)
                    .replace('\r', '')
                    .replace('\n', '')
                )
                subject = f'[{sender.name}] {subject}'

                message.subject = subject
                message.save()

                with get_connection(**connection_args) as connection:
                    msg = EmailMultiAlternatives(
                        bcc=[member.email for member in mailing_list.members.all()],
                        body=message.text,
                        connection=connection,
                        from_email=from_email.replace(',', ''),     # Can't have commas
                        headers={
                            'From': from_email,
                            'List-Archive': f'<{settings.SITE_URL}{reverse("mailing_lists:archive_list")}>',
                            'List-Help': (
                                f'<{settings.SITE_URL}{reverse("mailing_lists:lists")}>,'
                                f'<mailto:{settings.DEFAULT_FROM_EMAIL}?subject=help%20{sender.name}>'
                            ),
                            'List-Owner': f'<mailto:{settings.DEFAULT_FROM_EMAIL}> (Contact Person for Help)',
                            'List-Post': f'<mailto:{mailing_list.email}>',
                            'List-Subscribe': f'<mailto:{settings.DEFAULT_FROM_EMAIL}?subject=subscribe%20{sender.name}>',
                            'List-Unsubscribe': f'<mailto:{settings.DEFAULT_FROM_EMAIL}?subject=unsubscribe%20{sender.name}>',
                            'Message-ID': message.message_id,
                            'Sender': f'{sender.name} <{mailing_list.bounce_email}>',
                            'X-Hh-Beenthere': mailing_list.email,
                            'X-Sender': f'{sender.name} <{mailing_list.bounce_email}>'
                        },
                        reply_to=(message.from_header,),
                        subject=subject,
                        to=[f'{sender.name} <{mailing_list.email}>']
                    )

                    if email_object.get('In-Reply-to') is not None:
                        msg.extra_headers['In-Reply-To'] = \
                            email_object['In-Reply-to'].replace('\r\n', ' ').replace('\n', '')

                    if email_object.get('References') is not None:
                        msg.extra_headers['References'] = \
                            email_object['References'].replace('\r\n', ' ').replace('\n', '')

                    if message.html:
                        msg.attach_alternative(autolink_html(cleaner.clean_html(message.html)), 'text/html')

                    for att in message.attachments.all():
                        # noinspection PyProtectedMember
                        msg.attach(
                            filename=att.get_filename(), content=att.document.read(),
                            mimetype=att._get_rehydrated_headers().get_content_type()
                        )

                    try:
                        msg.send()
                    except (BadHeaderError, SMTPSenderRefused) as e:
                        msg.send()
                        logger.error(f'Error sending email with subject "{subject}": {e}')
            else:
                # Save the message to our reject pile (easier to view just rejected messages or to remove when
                # viewing ML archives)
                RejectedMessage.objects.create(message=message)

                # Log the issue and respond
                logger.info(f'{message.from_header} is not allowed to post to the {sender.name} list')

                msg = f'''\
Dear {message.from_header},

Your message to the {sender.name} list has been automatically rejected.

You are not authorized to post to this mailing list because your email
address is not subscribed. This list only accepts posts from subscribed
members.

If you believe this is incorrect, or you would like to request permission
to post, please contact the list administrator at:

{mailing_list.owner_email}

-----------------------------------------------------------------------

Reason for rejection:

Post by non-member to a members-only list.

---------------------------------------------------------------

Original message information:

Subject: {message.subject}

{message.text}
'''

                with get_connection(**connection_args) as connection:
                    msg = EmailMessage(
                        body=msg,
                        connection=connection,
                        from_email=mailing_list.bounce_email,
                        headers={
                            'From': mailing_list.email,
                            'Sender': mailing_list.bounce_email,
                            'X-Sender': mailing_list.bounce_email
                        },
                        subject=f'Your message to {sender.name} was rejected',
                        to=[message.from_header]
                    )

                    try:
                        msg.send()
                    except Exception as e:
                        logger.error(f'Error sending rejection email to "{message.from_header}": {e}')

templates/mailing_lists/_thread.html
{% for thread, children in threads.items %}
    <ul>
        <li>
            <a href="{% url "mailing_lists:message" thread.0 %}" target="_blank">
                {{ thread.1 }}
            </a>
            <span style="font-size: 80%; padding-left: 0.5em;"><em>({{ thread.2 }})</em></span>

            {% include "mailing_lists/_thread.html" with threads=children %}
        </li>
    </ul>
{% endfor %}

templates/mailing_lists/archive_list.html
{% extends "residents/base.html" %}
{% load static %}

{% block residents_title %}Archive List{% endblock %}
{% block header %}Archive List{% endblock %}

{% block css %}

{% endblock %}

{% block resident_content %}
    <p>The following mailing list archives are available:</p>

    <ol>
        {% for ml in object_list %}
            <li><a href="{% url 'mailing_lists:archives' ml.name_slug %}">{{ ml.mailbox.name }}</a></li>
        {% endfor %}
    </ol>
{% endblock %}

templates/mailing_lists/archives.html
{% extends "residents/base.html" %}
{% load replace %}
{% load static %}

{% block title %}The {{ ml_name }} Archives{% endblock %}
{% block header %}The {{ ml_name }} Archives{% endblock %}

{% block css %}
    {{ block.super }}
    
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #ddd;
            text-align: center;
        }

        th {
            background-color: #04AA6D;
            color: white;
            padding-bottom: 12px;
            padding-top: 12px;
        }
    </style>
{% endblock %}

{% block resident_content %}
    <table>
        <tr>
            <th>Archive</th>
            <th>View By</th>
        </tr>

        {% for archive in archives %}
            <tr>
                <td>{{ archive }}</td>
                <td>
                    <a href="{% url "mailing_lists:by_thread" ml_name_slug archive|replace:" |_" %}">[ Thread ]</a>
                    <a href="{% url "mailing_lists:by_subject" ml_name_slug archive|replace:" |_" %}">[ Subject ]</a>
                    <a href="{% url "mailing_lists:by_author" ml_name_slug archive|replace:" |_" %}">[ Author ]</a>
                    <a href="{% url "mailing_lists:by_date" ml_name_slug archive|replace:" |_" %}">[ Date ]</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/mailing_lists/by_author.html
{% extends "residents/base.html" %}
{% load static %}

{% block title %}The {{ ml_name }} {{ archive }} Archive by author{% endblock %}
{% block header %}{{ archive }} Archives by author{% endblock %}

{% block resident_content %}
    <p>
        <strong>Sort messages by</strong>:
        <a href="{% url "mailing_lists:by_thread" ml_name_slug archive %}">[ Thread ]</a>
        <a href="{% url "mailing_lists:by_subject" ml_name_slug archive %}">[ Subject ]</a>
        <a href="{% url "mailing_lists:by_date" ml_name_slug archive %}">[ Date ]</a>
    </p>

    <ul>
        {% for message in object_list %}
            <li>
                <a href="{% url "mailing_lists:message" message.0 %}" target="_blank">{{ message.1 }}</a>
                <span style="font-size: 80%; padding-left: 0.5em;"><em>({{ message.2 }})</em></span>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/mailing_lists/by_date.html
{% extends "residents/base.html" %}
{% load static %}

{% block title %}The {{ ml_name }} {{ archive }} Archive by date{% endblock %}
{% block header %}{{ archive }} Archives by date{% endblock %}

{% block resident_content %}
    <p>
        <strong>Sort messages by</strong>:
        <a href="{% url "mailing_lists:by_thread" ml_name_slug archive %}">[ Thread ]</a>
        <a href="{% url "mailing_lists:by_subject" ml_name_slug archive %}">[ Subject ]</a>
        <a href="{% url "mailing_lists:by_author" ml_name_slug archive %}">[ Author ]</a>
    </p>

    <ul>
        {% for message in object_list %}
            <li>
                <a href="{% url "mailing_lists:message" message.0 %}" target="_blank">{{ message.1 }}</a>
                <span style="font-size: 80%; padding-left: 0.5em;"><em>({{ message.2 }})</em></span>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/mailing_lists/by_subject.html
{% extends "residents/base.html" %}
{% load static %}

{% block title %}The {{ ml_name }} {{ archive }} Archive by subject{% endblock %}
{% block header %}{{ archive }} Archives by subject{% endblock %}

{% block resident_content %}
    <p>
        <strong>Sort messages by</strong>:
        <a href="{% url "mailing_lists:by_thread" ml_name_slug archive %}">[ Thread ]</a>
        <a href="{% url "mailing_lists:by_author" ml_name_slug archive %}">[ Author ]</a>
        <a href="{% url "mailing_lists:by_date" ml_name_slug archive %}">[ Date ]</a>
    </p>

    <ul>
        {% for message in object_list %}
            <li>
                <a href="{% url "mailing_lists:message" message.0 %}" target="_blank">{{ message.1 }}</a>
                <span style="font-size: 80%; padding-left: 0.5em;"><em>({{ message.2 }})</em></span>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/mailing_lists/by_thread.html
{% extends "residents/base.html" %}
{% load static %}

{% block title %}The {{ ml_name }} {{ archive }} Archive by thread{% endblock %}
{% block header %}{{ archive }} Archives by thread{% endblock %}

{% block resident_content %}
    <p>
        <strong>Sort messages by</strong>:
        <a href="{% url "mailing_lists:by_subject" ml_name_slug archive %}">[ Subject ]</a>
        <a href="{% url "mailing_lists:by_author" ml_name_slug archive %}">[ Author ]</a>
        <a href="{% url "mailing_lists:by_date" ml_name_slug archive %}">[ Date ]</a>
    </p>

    {% include "mailing_lists/_thread.html" %}
{% endblock %}

templates/mailing_lists/lists.html
{% extends "residents/base.html" %}
{% load static %}

{% block residents_title %}Mailing Lists{% endblock %}
{% block header %}Mailing Lists{% endblock %}

{% block css %}
    {{ block.super }}
    
    <style>
        li {
            margin-bottom: 1em;
        }
    </style>
{% endblock %}

{% block resident_content %}
    <p>There are currently six mailing lists:</p>
    
    <ol>
        <li>
            <dl>
                <dt><a href="mailto:board@huntingtonhillsinc.org">board@huntingtonhillsinc.org</a></dt>
                <dd>
                    This list is used to communicate to the current Huntington Hills board. If you send an email
                    from the <a href="{% url 'contact:contact' %}" >Contact</a> page to the board, 
                    this is the email that is used. You may also use it directly. Emails send to this address need
                    to be approved to reduce the amount of spam that is sent to board members. All non-spam emails
                    are always approved.
                </dd>
            </dl>
        </li>
        
        <li>
            <dl>
                <dt><a href="mailto:center@huntingtonhillsinc.org">center@huntingtonhillsinc.org</a></dt>
                <dd>
                    This list is only for those residents that live on Center Entrance.
                </dd>
            </dl>
        </li>
                
        <li>
            <dl>
                <dt>notices@huntingtonhillsinc.org</dt>
                <dd>
                    This list is used by the board to send official messages (like notice of the annual meeting for example). Only
                    board members can send messages to this list.
                </dd>
            </dl>
        </li>
                
        <li>
            <dl>
                <dt><a href="mailto:residents@huntingtonhillsinc.org">residents@huntingtonhillsinc.org</a></dt>
                <dd>
                    This list is meant to be used by Huntington Hills
                    residents to communicate with each other.  You can only send a
                    message from your subscribed email (the email you receive list messages).
                </dd>
            </dl>
        </li>
                
        <li>
            <dl>
                <dt><a href="mailto:spring_valley@huntingtonhillsinc.org">spring_valley@huntingtonhillsinc.org</a></dt>
                <dd>
                    This list is only for those residents that live on Spring Valley Drive.
                </dd>
            </dl>
        </li>
        
        <li>
            <dl>
                <dt>website-updates@huntingtonhillsinc.org</dt>
                <dd>
                    Announcements about changes or updates to the
                    Huntington Hills website are communicated with this list.
                     Only the webmaster can send messages to this list.
                </dd>
            </dl>
        </li>
    </ol>
{% endblock %}

templates/mailing_lists/message.html
{% extends "residents/base.html" %}
{% load static %}

{% block title %}{{ object }}{% endblock %}
{% block header %}{{ object }}{% endblock %}

{% block css %}
    {{ block.super }}

    <style>
        th {
            text-align: right;
        }
    </style>
{% endblock %}

{% block resident_content %}
    <table>
        <tr>
            <th>From:</th>
            <td>{{ object.from_header }}</td>
        </tr>

        <tr>
            <th>To:</th>
            <td>{{ object.to_header }}</td>
        </tr>

        <tr>
            <th>Subject:</th>
            <td>{{ object.subject }}</td>
        </tr>

        <tr>
            <th>Date:</th>
            <td>{{ date }}</td>
        </tr>

        <tr>
            <td colspan="2"><hr /></td>
        </tr>

        <tr>
            <td colspan="2">{{ object.text|linebreaks }}</td>
        </tr>
    </table>
{% endblock %}