apps/contact/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import ContactFormView


app_name = 'contact'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='contact/contact.html'), name='contact'),
    url(r'^adam/$', ContactFormView.as_view(), {'recipient': 'Adam Stein'}, name='adam'),
    url(r'^board/$', ContactFormView.as_view(), {'recipient': 'Board'}, name='board'),
    url(r'^webmaster/$', ContactFormView.as_view(), {'recipient': 'Webmaster'}, name='webmaster')
]

apps/docs/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


app_name = 'docs'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='docs/docs.html'), name='docs'),
    url(
        r'^combined_libraries/$',
        TemplateView.as_view(template_name='docs/Combined_Libraries.html'),
        name='combined_libraries')
]

apps/gallery/urls.py
from django.conf.urls import url

from .views import GalleryView, OwnerView, PageView

app_name = 'gallery'
urlpatterns = [
    url(r'^$', GalleryView.as_view(), name='gallery'),
    url(r'^(?P<slug>[\w-]+)/$', OwnerView.as_view(), name='owner'),
    url(r'^(?P<owner_slug>[\w-]+)/page/(?P<page_num>\d+)/$', PageView.as_view(), name='page')
]

apps/history/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


app_name = 'history'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='history/history.html'), name='history'),
    url(
        r'^irondequoit_story/$',
        TemplateView.as_view(template_name='history/irondequoit_story.html'),
        name='irondequoit_story'
    ),
url(
        r'^poetry/$',
        TemplateView.as_view(template_name='history/poetry.html'),
        name='poetry'
    ),
    url(
        r'^rochester_ski_club/$',
        TemplateView.as_view(template_name='history/rochester_ski_club.html'),
        name='rochester_ski_club'
    )
]

hh/urls.py
"""hh URL Configuration
"""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView

from library.views.generic import ProtectedMedia

urlpatterns = ([
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authentication.urls')),
    url(r'^bow_hunt/', include('bow_hunt.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^history/', include('history.urls')),
    url(r'^mailing_lists/', include('mailing_lists.urls')),
    url(r'^media/members/(?:.*)$', ProtectedMedia.as_view(), name='media'),
    url(r'^news/', include('news.urls')),
    url(r'^resident/', include('residents.urls')),
    url(r'^search/$', TemplateView.as_view(template_name='search.html'), name='search'),
    url(r'^staff/', include('staff.urls')),
    url(r'^technical/$', TemplateView.as_view(template_name='technical.html'), name='technical'),
    url(r'^tinymce/', include('tinymce.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

apps/gallery/models.py
from io import BytesIO
from os import path

from PIL import Image

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.base import ContentFile
from django.db import models
from django.utils.text import slugify

TNAIL_BACKGROUND_HEIGHT = 119
TNAIL_BACKGROUND_WIDTH = 119


def gallery_path(instance, filename):
    return f'gallery/{instance.owner.slug}/{instance.page}/{filename}'


def gallery_tnail_path(instance, filename):
    return f'gallery/{instance.owner.slug}/{instance.page}/tnail/{filename}'


class Owner(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(editable=False, unique=True)

    @property
    def num_pages(self):
        return self.photo_set.values_list('page', flat=True).order_by('page').distinct().count()

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(**kwargs)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Photo(models.Model):
    height = models.PositiveIntegerField(editable=False)
    image = models.ImageField(height_field='height', upload_to=gallery_path, width_field='width')
    long_description = models.TextField(blank=True)
    owner = models.ForeignKey('Owner')
    page = models.PositiveSmallIntegerField()
    short_description = models.CharField(blank=True, max_length=80)
    tnail = models.ImageField(
        editable=False, height_field='tnail_height', upload_to=gallery_tnail_path, width_field='tnail_width'
    )
    tnail_height = models.PositiveIntegerField(editable=False)
    tnail_width = models.PositiveIntegerField(editable=False)
    width = models.PositiveIntegerField(editable=False)

    class Meta:
        ordering = ('owner', 'page', 'image')

    @property
    def tnail_margin_top(self):
        return int(TNAIL_BACKGROUND_HEIGHT / 2 - self.tnail_height / 2)

    def save(self, **kwargs):
        image = Image.open(self.image if self.pk is None else self.image.path)
        image.thumbnail((TNAIL_BACKGROUND_WIDTH, TNAIL_BACKGROUND_HEIGHT))

        buffer = BytesIO()
        image.save(fp=buffer, format='PNG')
        tnail = ContentFile(buffer.getvalue())
        filename, _ = path.splitext(path.basename(self.image.name))
        filename += '.png'

        self.tnail.save(
            filename,
            InMemoryUploadedFile(
                tnail,              # file
                None,               # field_name
                filename,           # file name
                'image/jpeg',       # content_type
                tnail.tell,         # size
                None                # content_type_extra
            ),
            save=False
        )

        super().save(**kwargs)

    def __str__(self):
        return f'[{self.owner}/{self.page}] {self.short_description}'

apps/gallery/views.py
from django.views.generic import DetailView, ListView

from .models import TNAIL_BACKGROUND_HEIGHT, TNAIL_BACKGROUND_WIDTH, Owner, Photo


class GalleryView(ListView):
    model = Owner
    template_name = 'gallery/gallery.html'


class OwnerView(DetailView):
    model = Owner
    template_name = 'gallery/owner.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner_list'] = Owner.objects.all()
        context['pages'] = [f'Page {page_num}' for page_num in range(1, self.object.num_pages + 1)]

        return context


class PageView(ListView):
    model = Photo
    template_name = 'gallery/page.html'

    def get_context_data(self, **kwargs):
        owner = Owner.objects.get(slug=self.kwargs['owner_slug'])
        kwargs['object_list'] = Photo.objects.filter(owner=owner, page=self.kwargs['page_num'])
        context = super().get_context_data(**kwargs)
        context['box_size'] = (TNAIL_BACKGROUND_WIDTH, TNAIL_BACKGROUND_HEIGHT)
        context['object'] = owner
        context['owner_list'] = Owner.objects.all()
        context['page_num'] = self.kwargs['page_num']

        return context

templates/gallery/gallery.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=us-ascii" />
        <meta name="description" content="Photographs of Huntington Hills" />

        <title>{% block gallery_title %}Huntington Hills Gallery{% endblock %}</title>

        <link href="{% static "css/photogenic.css" %}" rel="stylesheet" type="text/css" />
    </head>

    <body style="direction: ltr;">
        <div id="wrapper">
            <div id="header">
                <h1>Gallery</h1>
            </div>

            <div id="navigation">
                <span><span>{% block nav %}Gallery{% endblock %}</span></span>
            </div>

            <div id="right">
                {% block gallery_content %}<h2>Click on a name to see photos</h2>{% endblock %}
            </div>

            <div id="left">
                <h1><span>List of Submitters</span></h1>

                <p>
                    <span>
                        Photographic images are available in the Gallery.
                        <a href="http://www.youtube.com/channel/UCMizLaUidrOfovnrgCaIP7A/videos?view=0" target="_blank">Videos
                        </a> are stored on <a href="http://www.youtube.com/" target="_blank">YouTube</a>.<br />
                    </span>
                </p>

                <p>
                    <span>
                        Click on an image to see the full sized version. Hover the mouse over the image to see a
                        description.
                    </span>
                </p>

                <p>
                    <span>
                        Please send all images or videos to <a href="mailto:adam@huntingtonhillsinc.org">Adam Stein</a>.
                        Submissions may be made by email (either the files or the locations to fetch them), CD, DVD,
                        USB stick, etc. (any media should be fine). Also include long and short descriptions as to
                        the contents of the files.<br />
                    </span>
                </p>

                <p>
                    <span>
                        All pictures are copyrighted by their respective owners unless otherwise noted.
                    </span>
                </p>

                {% if owner_list %}
                    <ol>
                        {% for owner in owner_list %}
                            <li>
                                {% ifequal owner object %}
                                    {{ owner.name }}
                                {% else %}
                                    <a href="{% url 'gallery:owner' owner.slug %}">{{ owner.name }}</a>
                                {% endifequal %}
                            </li>
                        {% endfor %}
                    </ol>
                {% else %}
                    <p>
                        <span>
                            There are currently no photographs online at this time.
                        </span>
                    </p>
                {% endif %}

                {% comment %}Easy way to get some padding at bottom of "left" container{% endcomment %}
                <p style="line-height: 1em;">&nbsp;</p>
            </div>

            <div id="footer">
                <span>
                    <a href="{% url "home" %}">Home</a> |
                    <a href="{% url "about" %}">About</a> |
                    <a href="{% url "docs:docs" %}">Documents</a> |
                    <a href="{% url "history:history" %}">History</a> |
                    Gallery |
                    <a href="{% url "contact:contact" %}">Contact</a> |
                    <a href="{% url "search" %}">Search</a> |
                    <a href="{% url "technical" %}">Technical Details</a>
                </span>
            </div>

            <div id="wrapper">
                <span class="credit">
                    design by <a href="http://www.oswd.org/user/profile/id/6360" target="_blank">Jack</a> |
                    content by Huntington Hills Association, Inc. (All Rights Reserved)
                </span>
            </div>
        </div>
    </body>
</html>

templates/gallery/owner.html
{% extends "gallery/gallery.html" %}

{% block gallery_title %}{{ object.name }}'s Photographs{% endblock %}

{% block nav %}
    <a href="{% url 'gallery:gallery' %}">Gallery</a>&#8250;&#8250;&nbsp;&nbsp;{{ object.name }}
{% endblock %}

{% block gallery_content %}
    <h2>{{ object.name }}'s Pictures</h2>

    <ul class="pagelist">
        {% for page in pages %}
            <li><a href="{% url 'gallery:page' object.slug forloop.counter %}">{{ page }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/gallery/page.html
{% extends "gallery/gallery.html" %}

{% block gallery_title %}{{ object.name }}'s Photographs (Page {{ page_num }}){% endblock %}

{% block nav %}
    <a href="{% url 'gallery:gallery' %}">Gallery</a>&#8250;&#8250;
    <a href="{% url 'gallery:owner' object.slug %}">{{ object.name }}</a>&#8250;&#8250;&nbsp;&nbsp;{{ page_num }}
{% endblock %}

{% block gallery_content %}
    <h2>Photos</h2>

    <ul class="gallery">
        {% for photo in photo_list %}
            <li>
                <a target="_blank" href="{{ photo.image.url }}"
                   style="height: {{ box_size.1 }}px; width: {{ box_size.0 }}px;">
                    <img alt="{{ photo.short_description }}"
                         style="height: {{ photo.tnail_height }}px; margin-top: {{ photo.tnail_margin_top }}px; width: {{ photo.tnail_width }}px;"
                         src="{{ photo.tnail.url }}" />
                    <span>
                        <em>{{ photo.short_description }}</em>
                        {{ photo.long_description|safe }}
                    </span>
                </a>
            </li>
        {% endfor %}
{% endblock %}